import type { MemberProfileData } from "@/components/Profile/types";

// In production, replace this with real reads from `users`, `member_profiles`,
// `member_skills` (joined to `skills`) and `projects` (joined to
// `project_members`) for the given username. The shape below is intentionally
// identical to those joins so swapping in real queries is a drop-in change.
const MEMBERS: Record<string, MemberProfileData> = {
  "arman-kian": {
    user: {
      id: 14,
      email: "arman@devinso.dev",
      role: "MEMBER",
      status: "ACTIVE",
      createdAt: "2024-02-11",
    },
    profile: {
      id: 9,
      userId: 14,
      username: "arman-kian",
      fullName: "Arman Kian",
      fullNameFa: "آرمان کیان",
      title: "Creative Full-Stack Engineer",
      titleFa: "مهندس خلاق فول‌استک",
      bio: "Full-stack engineer working across interface, motion and infrastructure. Focused on interaction systems that feel constructed, not decorated.",
      bioFa: "مهندس فول‌استک با تمرکز بر رابط کاربری، موشن و زیرساخت. علاقه‌مند به سیستم‌های تعاملی که ساخته‌شده به‌نظر برسند، نه تزئین‌شده.",
      currentFocus: ["Interaction systems", "Realtime interfaces", "Creative infrastructure"],
      currentFocusFa: ["سیستم‌های تعاملی", "رابط‌های بلادرنگ", "زیرساخت خلاق"],
      availability: "AVAILABLE",
      resumeUrl: "https://armankian.dev/resume",
      avatar: "",
      phone: "+98 912 000 0000",
      location: "Tehran, Iran",
      locationFa: "تهران، ایران",
      linkedin: "https://linkedin.com/in/armankian",
      github: "https://github.com/armankian",
      website: "https://armankian.dev",
      theme: { id: 3, name: "Verdant Signal", slug: "verdant-signal" },
    },
    experiences: [
      {
        id: 1,
        company: "DEVINSO",
        role: "Lead Creative Engineer",
        roleFa: "مهندس ارشد خلاق",
        period: "2024 — NOW",
        periodFa: "۱۴۰۳ — اکنون",
        description: "Leading interface architecture, motion direction and the systems that connect product design to production code.",
        descriptionFa: "هدایت معماری رابط، موشن و سیستم‌هایی که طراحی محصول را به کد نهایی متصل می‌کنند.",
        current: true,
      },
      {
        id: 2,
        company: "ALLIXRO",
        role: "Product Engineer",
        roleFa: "مهندس محصول",
        period: "2022 — 2024",
        periodFa: "۱۴۰۱ — ۱۴۰۳",
        description: "Built modular product surfaces and interaction patterns for automation-heavy workflows.",
        descriptionFa: "ساخت رابط‌های ماژولار و الگوهای تعاملی برای جریان‌های کاری مبتنی بر اتوماسیون.",
      },
      {
        id: 3,
        company: "INDEPENDENT",
        role: "Creative Developer",
        roleFa: "توسعه‌دهنده خلاق",
        period: "2020 — 2022",
        periodFa: "۱۳۹۹ — ۱۴۰۱",
        description: "Partnered with small teams to turn early visual concepts into expressive, production-ready web experiences.",
        descriptionFa: "همکاری با تیم‌های کوچک برای تبدیل ایده‌های بصری اولیه به تجربه‌های وب آماده انتشار.",
      },
    ],
    skills: [
      { id: 1, level: "EXPERT", skill: { id: 1, name: "TypeScript", category: "Language" } },
      { id: 2, level: "EXPERT", skill: { id: 2, name: "React", category: "Frontend" } },
      { id: 3, level: "ADVANCED", skill: { id: 3, name: "Next.js", category: "Frontend" } },
      { id: 4, level: "ADVANCED", skill: { id: 4, name: "GSAP", category: "Motion" } },
      { id: 5, level: "INTERMEDIATE", skill: { id: 5, name: "WebGL", category: "Motion" } },
      { id: 6, level: "ADVANCED", skill: { id: 6, name: "Node.js", category: "Backend" } },
      { id: 7, level: "INTERMEDIATE", skill: { id: 7, name: "PostgreSQL", category: "Backend" } },
      { id: 8, level: "BEGINNER", skill: { id: 8, name: "Go", category: "Backend" } },
      { id: 9, level: "ADVANCED", skill: { id: 9, name: "Figma", category: "Design" } },
    ],
    languages: [
      { id: 1, name: "Persian", nameFa: "فارسی", proficiency: "NATIVE" },
      { id: 2, name: "English", nameFa: "انگلیسی", proficiency: "PROFESSIONAL" },
      { id: 3, name: "Turkish", nameFa: "ترکی", proficiency: "CONVERSATIONAL" },
    ],
    tools: [
      { id: 1, name: "Figma", category: "DESIGN" },
      { id: 2, name: "VS Code", category: "BUILD" },
      { id: 3, name: "GitHub", category: "SHIP" },
      { id: 4, name: "Linear", category: "PLAN" },
      { id: 5, name: "Notion", category: "DOCS" },
      { id: 6, name: "Postman", category: "API" },
      { id: 7, name: "Docker", category: "INFRA" },
      { id: 8, name: "Vercel", category: "DEPLOY" },
    ],
    education: [
      {
        id: 1,
        institution: "University of Tehran",
        institutionFa: "دانشگاه تهران",
        degree: "Bachelor of Science",
        degreeFa: "کارشناسی",
        field: "Computer Engineering",
        fieldFa: "مهندسی کامپیوتر",
        period: "2018 — 2022",
        periodFa: "۱۳۹۷ — ۱۴۰۱",
      },
      {
        id: 2,
        institution: "Tehran Institute of Technology",
        institutionFa: "مؤسسه فناوری تهران",
        degree: "Professional Certificate",
        degreeFa: "گواهینامه حرفه‌ای",
        field: "Interactive Media",
        fieldFa: "رسانه‌های تعاملی",
        period: "2022 — 2023",
        periodFa: "۱۴۰۱ — ۱۴۰۲",
      },
    ],
    signals: [
      { id: 1, label: "TIMEZONE", labelFa: "منطقه زمانی", value: "UTC +03:30", valueFa: "UTC +03:30" },
      { id: 2, label: "WORK MODE", labelFa: "شیوه همکاری", value: "ASYNC FIRST", valueFa: "همکاری غیرهمزمان" },
      { id: 3, label: "PREFERRED LOOP", labelFa: "چرخه مطلوب", value: "BUILD / REFINE / SHIP", valueFa: "ساخت / بهبود / انتشار" },
    ],
    projects: [
      {
        id: 21,
        title: "ALLIXRO / RED PROFILE",
        description:
          "Art direction and cover system built around a fixed 16:9 media frame for member-replaceable covers.",
        descriptionFa: "آرت دایرکشن و سیستم کاور بر پایه یک قاب رسانه‌ای ثابت 16:9 برای جایگزینی آسان توسط اعضا.",
        outcome: "A reusable cover workflow with consistent art direction across releases.",
        outcomeFa: "یک جریان قابل‌استفاده مجدد برای حفظ آرت دایرکشن یکپارچه در انتشارها.",
        featured: true,
        coverImage: "/projects/allixro-cover-1920x1080.jpg",
        projectUrl: "https://devinso.dev/work/allixro",
        githubUrl: "https://github.com/devinso/allixro",
        techStack: ["Next.js", "GSAP", "Design"],
        type: "TEAM",
        status: "PUBLISHED",
        createdAt: "2026-01-14",
        membership: { role: "Art Direction + Cover System", roleFa: "آرت دایرکشن + سیستم کاور", joinedAt: "2025-11-02" },
      },
      {
        id: 22,
        title: "Automation Platform",
        description:
          "Modular control surface for orchestrating flows and monitoring nodes while keeping technical clarity intact.",
        descriptionFa: "سطح کنترل ماژولار برای مدیریت جریان‌ها و مانیتور نودها بدون از بین رفتن وضوح فنی.",
        outcome: "Unified complex monitoring states into one legible operator surface.",
        outcomeFa: "یکپارچه‌سازی وضعیت‌های پیچیده مانیتورینگ در یک رابط واضح برای اپراتور.",
        techStack: ["React", "Realtime API", "PostgreSQL"],
        type: "TEAM",
        status: "PUBLISHED",
        createdAt: "2025-09-02",
        membership: { role: "System Design + Development", roleFa: "طراحی سیستم + توسعه", joinedAt: "2025-06-18" },
      },
      {
        id: 23,
        title: "Personal Site Rebuild",
        description: "A from-scratch rebuild of a personal portfolio with a construction/blueprint visual system.",
        descriptionFa: "بازسازی کامل یک نمونه‌کار شخصی با سیستم بصری الهام‌گرفته از بلوپرینت.",
        outcome: "A modular visual language reusable across profile and project pages.",
        outcomeFa: "یک زبان بصری ماژولار و قابل‌استفاده در صفحات پروفایل و پروژه.",
        githubUrl: "https://github.com/armankian/portfolio",
        techStack: ["Next.js", "GSAP", "Tailwind"],
        type: "PERSONAL",
        status: "PUBLISHED",
        createdAt: "2025-03-20",
        membership: { role: "Solo build", roleFa: "ساخت انفرادی", joinedAt: "2025-01-05" },
      },
      {
        id: 24,
        title: "Realtime Kanban Engine",
        description: "In-progress board engine with optimistic sync and conflict-free drag ordering.",
        descriptionFa: "موتور بورد کانبان در حال توسعه با همگام‌سازی خوش‌بینانه و ترتیب بدون تداخل.",
        techStack: ["Go", "WebSocket", "React"],
        type: "PERSONAL",
        status: "DRAFT",
        createdAt: "2026-04-02",
        membership: { role: "Solo build", roleFa: "ساخت انفرادی", joinedAt: "2026-03-01" },
      },
    ],
  },
};

export function getMemberProfile(username: string): MemberProfileData | undefined {
  return MEMBERS[username];
}

export function listMemberUsernames(): string[] {
  return Object.keys(MEMBERS);
}
