export const UI_COPY = {
  en: {
    studioTagline: "Digital product team",
    nav: { work: "Work", studio: "Studio", contact: "Contact", settings: "Settings", aria: "Primary navigation" },
    settings: {
      eyebrow: "Interface",
      title: "Preferences",
      theme: "Theme",
      themeHint: "Preserves motion, glass and grid effects",
      language: "Language",
      languageHint: "Switches UI copy and mirrors the layout for Persian",
      themeLight: "Light",
      themeDark: "Dark",
      stateLight: "LIGHT",
      stateDark: "DARK",
      english: "EN",
      persian: "FA",
      displayAria: "Display settings",
    },
    ambient: { leftA: "signal.field", leftB: "grid / live", rightA: "construction.flow", rightB: "status = active" },
    stage: {
      label: "IDENTITY CONSTRUCTION",
      subtitle: "Design × Development × Interaction",
      description:
        "The DEVINSO mark reconstructed from its original design guides — the same geometry used to shape the identity, resolved into motion.",
      primaryAction: "Explore work",
      secondaryAction: "Start a project",
      services: ["Product", "Brand", "Creative dev"],
      capabilitiesAria: "Capabilities",
      buildStatus: "construction resolved",
      coords: "GRID // 1285.46 × 807.55 · AXIS 639.43",
      scroll: "SCROLL TO EXPLORE",
      footerTag: "DEVINSO / ORIGINAL CONSTRUCTION SYSTEM",
      loader: {
        status: "INITIALIZING EXPERIENCE",
        complete: "SYSTEM READY",
        lines: [
          "boot.sequence // start",
          "loading design.system",
          "binding motion.engine",
          "syncing interface.layer",
        ],
      },
    },
    dial: { title: "CONSTRUCTION DIAL", subtitle: "AXIS / GUIDE / RESOLVE" },
    code: {
      leftLabel: "identity.ts",
      leftLines: [
        'const studio = defineStudio();',
        'studio.add("design");',
        'studio.add("code");',
        'studio.add("motion");',
        'export const devinso = studio.compile();',
      ],
      rightLabel: "construction.grid",
      rightLines: [
        'guides.load(original);',
        'axis.lock(639.43);',
        'mark.align(guides);',
        'stroke.resolve();',
        'identity.commit();',
      ],
      bottomLabel: "system / ready",
      bottomLines: [
        ['</>', 'type Identity = "DEVINSO";'],
        ['//', 'source: original-grid · alignment: preserved'],
      ],
    },
    grid: { axis: "AXIS 639.43", original: "ORIGINAL CONSTRUCTION", guide: "GUIDE / 01" },
    notes: { topA: "Original guides", topB: "aligned", rightA: "Center axis", rightB: "639.43", bottomA: "Identity", bottomB: "resolved" },
  },
  fa: {
    studioTagline: "تیم طراحی محصول دیجیتال",
    nav: { work: "نمونه‌کار", studio: "استودیو", contact: "تماس", settings: "تنظیمات", aria: "ناوبری اصلی" },
    settings: {
      eyebrow: "رابط",
      title: "تنظیمات",
      theme: "تم",
      themeHint: "حرکت، شیشه و افکت‌های گرید حفظ می‌شوند",
      language: "زبان",
      languageHint: "رابط را فارسی می‌کند و چیدمان را قرینه می‌سازد",
      themeLight: "روشن",
      themeDark: "تاریک",
      stateLight: "روشن",
      stateDark: "تاریک",
      english: "EN",
      persian: "فا",
      displayAria: "تنظیمات نمایش",
    },
    ambient: { leftA: "signal.field", leftB: "grid / live", rightA: "construction.flow", rightB: "status = active" },
    stage: {
      label: "ساخت هویت",
      subtitle: "طراحی × توسعه × تعامل",
      description:
        "نشان DEVINSO با استفاده از گایدهای اصلی خود بازسازی شده؛ همان هندسه‌ای که هویت را شکل داده، اینجا به حرکت تبدیل شده است.",
      primaryAction: "مشاهده نمونه‌کارها",
      secondaryAction: "شروع پروژه",
      services: ["محصول", "برند", "توسعه خلاق"],
      capabilitiesAria: "توانمندی‌ها",
      buildStatus: "ساختار هویت آماده است",
      coords: "GRID // 1285.46 × 807.55 · AXIS 639.43",
      scroll: "برای ادامه اسکرول کنید",
      footerTag: "DEVINSO / سیستم ساخت اصلی",
      loader: {
        status: "در حال آماده‌سازی رابط",
        complete: "سیستم آماده است",
        lines: [
          "boot.sequence // start",
          "loading design.system",
          "binding motion.engine",
          "syncing interface.layer",
        ],
      },
    },
    dial: { title: "دایال ساخت", subtitle: "محور / گاید / نهایی‌سازی" },
    code: {
      leftLabel: "identity.fa",
      leftLines: [
        'const studio = defineStudio();',
        'studio.add("طراحی");',
        'studio.add("کد");',
        'studio.add("موشن");',
        'export const devinso = studio.compile();',
      ],
      rightLabel: "construction.fa",
      rightLines: [
        'guides.load(original);',
        'axis.lock(639.43);',
        'mark.align(guides);',
        'stroke.resolve();',
        'identity.commit();',
      ],
      bottomLabel: "سیستم / آماده",
      bottomLines: [
        ['</>', 'type Identity = "DEVINSO";'],
        ['//', 'منبع: گرید اصلی · هم‌ترازی: حفظ شده'],
      ],
    },
    grid: { axis: "AXIS 639.43", original: "ساختار اصلی", guide: "گاید / 01" },
    notes: { topA: "گایدهای اصلی", topB: "هم‌تراز", rightA: "محور مرکزی", rightB: "639.43", bottomA: "هویت", bottomB: "نهایی" },
  },
} as const;

export type HeroCopy = (typeof UI_COPY)[keyof typeof UI_COPY];
